### ISSUE TITLE
Incorrect Server#getName value

### ISSUE THREAD

**Issue by md678685** [KettleFoundation/Kettle#10]
https://github.com/KettleFoundation/Kettle/blob/e461dd7cfe56619e4c35e9dde00d033b0c22d273/src/main/java/org/bukkit/craftbukkit/CraftServer.java#L427-L430

https://github.com/KettleFoundation/Kettle/blob/e461dd7cfe56619e4c35e9dde00d033b0c22d273/src/main/java/org/bukkit/craftbukkit/CraftServer.java#L177

Running `org.bukkit.Server#getName` on Kettle returns `"CraftBukkit"`, which is not an accurate description of the server. This method should return `"Kettle"` or similar in order to allow Bukkit plugins to accurately identify the real server software that is running instead of depending on unreliable heuristics.

**Comment by josephworks** [comment]
Yes, I agree. This might also fix the /version command.

Joseph R.

**Comment by Hexeption** [comment]
That makes sense ill change that 👍👍
