### ISSUE TITLE
Global Not-Per-Mod-Related Issues

### ISSUE THREAD

**Issue by Timardo** [KettleFoundation/Kettle#11]
These are the issues I found running a clean install with no mods nor plugins, I should add more later:

- [x] Any items are not taking any damage from any sources (except swords, see below) until they don't have Unbreaking enchantment of any level
- [x] Swords are taking only client side/visual damage when breaking "their special" blocks (see [wiki](https://minecraft.gamepedia.com/Sword#Sword_breaking_times) After relogging/opening any block's GUI/throwing it away and picking it up will regain it's damage value with which it appeared in player's inventory (even if broken!)
- [x] Mobs always drop double/~~triple~~ the loot they should (even wither bosses!)
- [x] Breaking skulls always give you 2 of them
- [x] Chunk dispatcher issues (flickering parts of world) (Redd56)
- [x] Placing modded blocks in creative is not synced with client (Redd56)
- [x] Shearing sheep doesn't yield any wool until killed

**Comment by Redd56** [comment]
Chunk dispatcher issues. 
Creative invintory not synced for modded blocks

**Comment by Redd56** [comment]
information updated to give more info

**Comment by Timardo** [comment]
Updated the list of issues since they should be fixed in the code now
