### ISSUE TITLE
Bukkit Related Issues

### ISSUE THREAD

**Issue by TheDaChicken** [KettleFoundation/Kettle#13]
These are the issues I ran into running Bukkit Plugins. (I will update if I find more)

- Bukkit.createWorld() causes a 'java.lang.IllegalArgumentException' [[PASTEBIN]](https://pastebin.com/raw/GBbL1Mm7)
To reproduce: Install Multiverse-core plugin and create a new world.
- Missing Bukkit Class 'net/minecraft/server/v1_12_R1/Packet' (I don't know if you guys are going to support Packet sending or not but I am going to put this here) [[PASTEBIN]](https://pastebin.com/raw/7hrrgcnD)
To reproduce: Install a Packet type plugin like Citizens on Startup, It will crash.
- Missing Bukkit Class 'net/minecraft/server/v1_12_R1/EntityZombie' 

Other than that, It works great.

**Comment by GMatrixGames** [comment]
NMS doesn't work yet, and World creation isn't functioning I don't believe.

**Comment by TheDaChicken** [comment]
That is what I thought.

**Comment by GMatrixGames** [comment]
NMS will be fixed in next update, and the Multiverse-Core issue should've been fixed a while ago

**Comment by GMatrixGames** [comment]
This has been fixed in the next build!

- GMatrixGames
