### ISSUE TITLE
Mods cannot load due to not detecting forge as a mod.

### ISSUE THREAD

**Issue by Orangian** [KettleFoundation/Kettle#20]
Here is the issue I am getting: 
![kettle cooker](https://user-images.githubusercontent.com/9283018/55299227-001acb80-5400-11e9-8926-92b60367a79b.PNG) 

As you can see in the red text, a few essential mods of mine are not loading due to not detecting forge. Log is linked below.
[latest.log](https://github.com/KettleFoundation/Kettle/files/3027497/latest.log)

**Comment by josephworks** [comment]
The issue is caused by outdated forge, please downgrade Morpheus and all of its dependencies.

**Comment by Orangian** [comment]
Oh. Thank you! I will try that.

**Comment by Orangian** [comment]
It worked! Question though, will the version of forge be able to be updated?

**Comment by josephworks** [comment]
soon

**Comment by Orangian** [comment]
Thanks!

**Comment by Cronosus** [comment]
have similar problem with outdated forge version
net.minecraftforge.fml.common.MissingModsException: Mod jei (Just Enough Items) requires [forge@[14.23.5.2816,)]
