### ISSUE TITLE
Installation problem there is no forge

### ISSUE THREAD

**Issue by MaxifeuxG** [KettleFoundation/Kettle#23]
Hello I followed the installation and the folder plugins and mods do not appear I made requests and I said forge do not settle for time I followed the instalation

pastebin link logs: https://pastebin.com/hU42v9x5

**Comment by Timardo** [comment]
`java -Xmx1024M -Xms1024M -jar minecraft_server.1.12.2.jar` - this is wrong, you have to run the kettle jar, rename the jar file starting with name `kettle` to other, more familiar name and rewrite the `minecraft_server.1.12.2.jar` part in the launch script with its new name. For reference, look at discord what I wrote to the kettle channel.

**Comment by MaxifeuxG** [comment]
yes thank you I followed what was said and it works
