### ISSUE TITLE
Couple of crashes with coremods Advanced rocketry and Chunk pregenerator

### ISSUE THREAD

**Issue by musicderp** [KettleFoundation/Kettle#26]
Sorry I can't be super specific as I don't have that much technical knowledge, but kettle crashes when I have Advanced Rocketry or ChunkPregenerator in my mod list.

Here are the crash logs from both

https://pastebin.com/yfcqkEv7
https://pastebin.com/Xx2PcR4g

**Comment by musicmanpwns** [comment]
Bump

**Comment by GMatrixGames** [comment]
The second issue is from Actually Additions, and should be fixed.
The first issue, seems to be a problem with ChunkPregenerator, if you could do some testing with the latest build, that would be great!

- GMatrixGames
