### ISSUE TITLE
Only have 1 mod Pokecube installed

### ISSUE THREAD

**Issue by Karagra** [KettleFoundation/Kettle#27]
https://pastebin.com/AJj4D0Sc

**Comment by Thutmose** [comment]
This issue is caused by the calling of EntityLiving.canDespawn, before the entity has finished constructing, This results in the capability which is being checked to be null.

**Comment by Thutmose** [comment]
I can make this stop happening on my end, but why is canDespawn called before the mob is fully constructed?
