### ISSUE TITLE
crash mods Vic's Modern Warfare Mod

### ISSUE THREAD

**Issue by MaxifeuxG** [KettleFoundation/Kettle#28]
mod links : https://minecraft.curseforge.com/projects/vics-modern-warfare-mod/files
mods version : Modern Warfare 1.11.7.7 mc1.12.2 RELEASE

Kettle version : Kettle Dev HEAD-b7c2f7d

Cash Report : 
(in pastbin = https://pastebin.com/MeKyjstK)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons.jar)
  weaponlib (mw.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 05/05/19 19:35
Description: Exception ticking world

java.lang.NoSuchMethodError: com.vicmatskiv.weaponlib.ai.EntityCustomMob.func_98053_h(Z)V
	at com.vicmatskiv.weaponlib.ai.EntityCustomMob.onCompatibleSpawn(EntityCustomMob.java:272)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleEntityMob.func_180482_a(CompatibleEntityMob.java:121)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:178)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:398)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:617)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.vicmatskiv.weaponlib.ai.EntityCustomMob.onCompatibleSpawn(EntityCustomMob.java:272)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleEntityMob.func_180482_a(CompatibleEntityMob.java:121)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:178)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:398)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Maxifeux'/328, l='world', x=-226,36, y=77,00, z=224,76](Maxifeux at -226.35776693585785,77.0,224.75569301276542)]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: -2015465900995999913
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-220,64,256), Chunk: (at 4,4,0 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 98823 game time, 98823 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 72667 (now: false), thunder time: 1310 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:617)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 110662136 bytes (105 MB) / 1410859008 bytes (1345 MB) up to 3814195200 bytes (3637 MB)
	JVM Flags: 3 total; -Xms128M -XX:+AggressiveOpts -Xloggc:gc.log
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2812 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version        | Source                             | Signature |
	|:------ |:----------------- |:-------------- |:---------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2         | minecraft.jar                      | None      |
	| LCHIJA | mcp               | 9.42           | minecraft.jar                      | None      |
	| LCHIJA | FML               | 8.0.99.99      | kettle.jar                         | None      |
	| LCHIJA | forge             | 14.23.5.2812   | kettle.jar                         | None      |
	| LCHIJA | cfm               | 6.2.0          | cfm-6.2.0-mc1.12.2.jar             | None      |
	| LCHIJA | extendedrenderer  | v1.0           | coroutil.jar                       | None      |
	| LCHIJA | coroutil          | 1.12.1-1.2.13  | coroutil.jar                       | None      |
	| LCHIJA | configmod         | v1.0           | coroutil.jar                       | None      |
	| LCHIJA | customnpcs        | 1.12           | CustomNPCs.jar                     | None      |
	| LCHIJA | flansmod          | 5.5.2          | Flan's Mod-1.12.2-5.5.2.jar        | None      |
	| LCHIJA | mw                | 1.11.7.7       | mw.jar                             | None      |
	| LCHIJA | sereneseasons     | 1.2.15         | SereneSeasons.jar                  | None      |
	| LCHIJA | toughasnails      | 3.1.0.140      | ToughAsNails.jar                   | None      |
	| LCHIJA | variedcommodities | 1.12.2         | VariedCommodities.jar              | None      |
	| LCHIJA | imvoice           | 0.7.0          | VoiceChat.jar                      | None      |
	| LCHIJA | wearablebackpacks | 3.1.3          | WearableBackpacks-1.12.2-3.1.3.jar | None      |
	| LCHIJA | zombieawareness   | 1.12.1-1.11.16 | zombieawareness.jar                | None      |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
weaponlib (mw.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Maxifeux'/328, l='world', x=-226,36, y=77,00, z=224,76](Maxifeux at -226.35776693585785,77.0,224.75569301276542)]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MaxifeuxG** [comment]
no it came from my version of the mod that was not up to date

**Comment by MaxifeuxG** [comment]
if the crash and still present but it's not the connection it and a little after

**Comment by Hexeption** [comment]
What does that mean?

**Comment by nicov420** [comment]
The problem is that the mod cant use forge above version 14.23.4.2758,you have to either use that,or a lower one. We need Kettle with forge with lower version than .2759 or update the modpack that probably wont happen. Its a great mod if not the best and im sure many people would love to use it. Is there any chance we can get a kettle with that older forge?

**Comment by Hexeption** [comment]
Forge has been updated
