### ISSUE TITLE
Conquest Reforged : Exception ticking world

### ISSUE THREAD

**Issue by GuusLieben** [KettleFoundation/Kettle#32]
The server crashes when loading certain crops (BerryBushBlock in Conquest Reforged).
Using the latest version of Kettle (Unstable 2 at the time of writing). Does this error throw for all modded crop types? Considering Pam's Harvestcraft and such.

Crash log : https://pastebin.com/kwp6ECmG

**Comment by Timardo** [comment]
This is caused by Bukkit as it is not able to obtain the material for this block, I made a quick fix and PR for this using code from Cauldron.

**Comment by kingdevnl** [comment]
@Timardo Please don't use code from Cauldron, We don't want to use any code from projects as
Cauldron, KCauldron, Thermos etc
