### ISSUE TITLE
crops ot growing

### ISSUE THREAD

**Issue by Cronosus** [KettleFoundation/Kettle#34]
hello
Crops/trees not growing on server
looks like randomTickSpeed  not working

**Comment by Cronosus** [comment]
ad. we also have some lightning bugs.. but not sure if its the same problem

**Comment by Cronosus** [comment]
also looks like BlockUpdate not working 
![2019-05-10_22 57 54](https://user-images.githubusercontent.com/5349950/57556904-94ba0700-7378-11e9-8cfc-a65cb4b3628d.png)
![2019-05-10_22 58 15](https://user-images.githubusercontent.com/5349950/57556906-95529d80-7378-11e9-98c8-9fb23cc6a7a3.png)

**Comment by hamsterben5** [comment]
Also experiencing these issues. Crops are not growing with Kettle.

**Comment by INSeoul** [comment]
I'm in trouble with the lightning bug and this problem.
