### ISSUE TITLE
java.lang.NoSuchMethodError thrown from the UncaughtExceptionHandler in thread "Server thread"

### ISSUE THREAD

**Issue by VanillaChan6571** [KettleFoundation/Kettle#35]
[latest.log](https://github.com/KettleFoundation/Kettle/files/3180715/latest.log)
[debug.log](https://github.com/KettleFoundation/Kettle/files/3180716/debug.log)

Unknown issue I don't know what the issue could be just crashes after launch.

**Comment by Timardo** [comment]
There is no crash in these logs, only bunch of errors which are not very important right now as we don't know if they are just informative or something is actually not working correctly.
