### ISSUE TITLE
Fatally missing registry entries

### ISSUE THREAD

**Issue by WitherTech** [KettleFoundation/Kettle#39]
I can’t log in to my server

**Comment by josephworks** [comment]
Ok, thanks for telling us. Please provide more information... Until then, you will NOT be provided support.

**Comment by WitherTech** [comment]
I figured it out
I removed a mod, but kettle wasn’t removing the items that no longer exist

**Comment by WitherTech** [comment]
I had to load the world in a singleplayer instance to clear them

**Comment by ConnorTron110** [comment]
This is normally a result of you not having a mod that the server has or you have removed a mod from the server and you still need to do /fml confirm to launch it, for some reason you still need the mod on the client side for you to join.

**Comment by WitherTech** [comment]
I did the fml confirm thing but it didn’t actually fix it
I had to load the server world on my client to clear all the stuff out of my world

**Comment by WitherTech** [comment]
I did remove a mod which is what caused this, but the server prompted me to do /fml confirm every time I started the server

**Comment by josephworks** [comment]
Just reset the server completely..

**Comment by ConnorTron110** [comment]
Mod that you removed, you require on the client otherwise it wont load

**Comment by WitherTech** [comment]
It loaded on the client

**Comment by WitherTech** [comment]
And i already fixed it

**Comment by ConnorTron110** [comment]
so its fixed?

**Comment by WitherTech** [comment]
I had to work around the problem

**Comment by GMatrixGames** [comment]
@WitherTech If this issue is solved, please close it to help Hex
