### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by musicmanpwns** [KettleFoundation/Kettle#43]
Hey, the discord link in the readme is expired, and would be great if that was renewed

**Comment by DragonsAscent** [comment]
> Hey, the discord link in the readme is expired, and would be great if that was renewed

As I just tested with an alt and confirmed in the settings of the discord itself, the invite it active and not expired. Try again or have this [one use](https://discord.gg/4DfdTnc).

![image](https://user-images.githubusercontent.com/24839115/60414263-9ef0c880-9ba5-11e9-8da5-ac13f95635f4.png)
