### ISSUE TITLE
Quark Method transforming error

### ISSUE THREAD

**Issue by Motzkiste** [KettleFoundation/Kettle#45]
Hi,

I tried moving my Modpack from SpongeForge to Kettle, because i really like the Spigot features.

A got an Error with Quark on Server start/load.
I think Quark tries to modify a Method that doesn't exist in Kettle.

[Error-Part from Serverlog](https://pastebin.com/vYKyGEvc)

I'm using latest Release-Version: 2579c45

I really hope something like this can be fixed.

Btw: You are doing a great Job here merging Spigot and Forge again ;)

**Comment by GMatrixGames** [comment]
Quark will pretty much never work on an implementation like this, especially since it barely functions on Forge alone.

It has to be recoded **EVERY** time forge updates because of so many method changes it makes using ASM.

- GMatrixGames

**Comment by Motzkiste** [comment]
So is there a way to bypass this?

Maybe disabling all Quark features that make methode changes?

**Comment by josephworks** [comment]
no, instead of disabling quark... Add compatibility?

**Comment by GMatrixGames** [comment]
I don't believe it wouldn't pay off to make Quark compat. As there are so many changes CraftBukkit has already made to the methods, it would be a lot of strenuous work to pull off.

(NOTE TO ANY OF THE KETTLE STAFF, THIS IS NOT AN ADVERTISEMENT, JUST A NOTE)
With making a Forge + Paper implementation myself, my team and I, if you're willing to wait, may be able to pull this off, and maybe pull request it to Kettle later on.

**Comment by Motzkiste** [comment]
Ok.

If you want you can close this issue, because i can't be fixed.
Or better: It's to much to do (compatibility). A waste of Time.

But really thank you for very fast reply.

I'll disable all not Client-Side features and let the server work without Quark ^^

I don't know if you want to let this issue open, because of considering if you want to add compatibility or not.
If not fell free to close this issue ^^

Thank you again :)

**Comment by GMatrixGames** [comment]
It performs really well, sadly, the developer of Kettle (Hex) hasn't done much of anything in terms of performance anything yet.
