### ISSUE TITLE
Problem with Paper's Waterfall and Kettle

### ISSUE THREAD

**Issue by Motzkiste** [KettleFoundation/Kettle#46]
Hi me again,

I've encountered another issue.

If I connect to Kettle without Waterfall everything works fine.
But if I try it through Waterfall I get kicked whilst connecting:
`This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.`

I've enabled IP-Forwarding and Forge support in Waterfall and Bungeecord support in spigot.yml from Kettle. And yes I disabled online-mode in Kettle, because IP-Forwarding requiers this.

Maybe I've forgotten something?

EDIT:
Ok, sry i've to say it does not work without Waterfall!
Error in Console: `[Server thread/INFO] [minecraft/NetHandlerPlayServer]: Motzkiste lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet`

EDIT 2:
Restarted Server again and it works without Waterfall. Don't know what went wrong the first time.

**Comment by GMatrixGames** [comment]
The issue has.been solved in my project Lava, the staff can feel free to use it, just give credit

**Comment by Motzkiste** [comment]
Ok Thank you.
I'll give it a try.

**Comment by Redd56** [comment]
Also broke in bungee. Ik theres a workaround but i forgot how to do it
