### ISSUE TITLE
Problem with setting up a Kettle server

### ISSUE THREAD

**Issue by RyanFlm** [KettleFoundation/Kettle#47]
Hey there..
just now I've tried to set up a Kettle server. But it didn't work correctly for me, because there is just the vanilla Minecraft server running. Maybe I've misunderstood the short instructions but I found no other and more detailed instruction.
So can somebody help me?

What I've done:
1. Download the universal.jar
2. Run this jar in an empty folder (to get all the files which are needed)
3. Set up the start script
4. Run the renamed universal.jar --> Failed
(5. Tried to run the minecraft-server.jar --> just vanilla minecraft)

Thanks for all coming suggestions!

**Comment by josephworks** [comment]
the Minecraft server jar is a vanilla jar..
Just use https://github.com/josephworks/KettleServer/archive/v1.1.zip
it is a premade server, just download src, unzip, and run the
startserver.bat
