### ISSUE TITLE
Actually Additions Crash

### ISSUE THREAD

**Issue by blacksythe** [KettleFoundation/Kettle#48]
[crash-2019-07-25_15.08.26-server.txt](https://github.com/KettleFoundation/Kettle/files/3431934/crash-2019-07-25_15.08.26-server.txt)

**Comment by zandercodes** [comment]
I know why it crashes.
Since the ItemStack is from Bukkit and is only Trap I assume that it is a TrapDoor and Trap cannot be found.
So you have to check it in the ItemStack.

**Comment by Hexeption** [comment]
Can you replicate this?

**Comment by zandercodes** [comment]
@Hexeption I know how it crashes. [This Line](https://github.com/KettleFoundation/Kettle/blob/0d08d1f13af22416de64cfbdc0325c3296505d43/patches/net/minecraft/item/ItemStack.java.patch#L90) in Minecraft Itemstack.
This line has been deleted in the new commit.
I think the problem is solved.

**Comment by blacksythe** [comment]
Will test this
