### ISSUE TITLE
tp command

### ISSUE THREAD

**Issue by GravitaBB** [KettleFoundation/Kettle#49]
If a player wants to teleport himself to another player, he is teleported to himself.

**Comment by DragonsAscent** [comment]
We'll need much more info.

- Are you using any plugins which are overriding the normal teleport?
- Do you mean `minecraft:tp @s <target>`?

**Comment by GravitaBB** [comment]
- No, I haven't installed any plugins. Just a few mods. But even without any mods, this issue appears.
- I mean the tp command which you enter in the chat ( /tp <target player> ).

**Comment by GMatrixGames** [comment]
Will do some testing, but should be fixed in next update

- GMatrixGames

**Comment by GMatrixGames** [comment]
EDIT: Fixed
