### ISSUE TITLE
Lights problem

### ISSUE THREAD

**Issue by SparkizX** [KettleFoundation/Kettle#52]
![image](https://user-images.githubusercontent.com/18197204/62480860-39e64f00-b7b1-11e9-86a6-061579679d6a.png)
This is the problem I have. Most of the chunks that will reload will have this.

**Comment by Timardo** [comment]
I guess you are loading an old modded world, am I right?

**Comment by SparkizX** [comment]
Nope, generated one using kettle on 1.12.2.

**Comment by SparkizX** [comment]
I switched to sponge forge and everything works like a charm now.

**Comment by GMatrixGames** [comment]
Fixed with next update.

- GMatrixGames
