### ISSUE TITLE
ID Limit Reached and server crashes

### ISSUE THREAD

**Issue by MackBaggins** [KettleFoundation/Kettle#56]
**Describe the bug**
java.lang.ArrayIndexOutOfBoundsException: 6378 when registering Block ID's

**Give us some details to work with*
Crash log (if any): https://pastebin.com/hZtdBZan
Location: material.java
Minecraft version: * 1.12.2
Forge version: * 14.23.5.2838
Kettle version: * kettle-git-HEAD-a752eab-universal

**To Reproduce**
1. Use Kettle a752eab
2. Have enough mods to use more than 6738 ID's
3. Watch it Crash

**Expected behavior**
Server launches with no ID limit being reached

**Screenshots (if any)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Professional

**Additional context**
can fix by changing material.java to allow more ID's

**Comment by GMatrixGames** [comment]
This is already planned for next update.

**Comment by GMatrixGames** [comment]
This has been fixed in the next build!

- GMatrixGames
