### ISSUE TITLE
Make gradle or jenkins output a plain kettle.jar

### ISSUE THREAD

**Issue by josephworks** [KettleFoundation/Kettle#71]
This way, update scripts will be possible...

This can also be a jenkins side thing too, cause that is where people download kettle jar from.

**Comment by GMatrixGames** [comment]
The reason it outputs like that is because it's the way ForgeGradle outputs a final jar.

**Comment by josephworks** [comment]
Well, can't we fix that with gradle?

**Comment by josephworks** [comment]
This will be fixed with the kettlefile
