### ISSUE TITLE
JEI \ CodeChickenLib and MW compatibility

### ISSUE THREAD

**Issue by byalexeykh** [KettleFoundation/Kettle#73]
Logs (JEI): https://paste.dimdev.org/elukebozif.mccrash
Logs (CodeChickenLib): https://paste.dimdev.org/odedekebiq.mccrash

VanillaFix warning: https://ibb.co/gZKFvvh

Game crashes when im trying to accept inventory (same to JEI and CodeChickenLib)

**Comment by GMatrixGames** [comment]
This is an issue that cannot be solved on our end, it is an incompatibility issue with Forge versions. Apologies for the inconvenience
