### ISSUE TITLE
Is this still alive ?

### ISSUE THREAD

**Issue by Aang23** [KettleFoundation/Kettle#8]
A simple question... If the answer is yes I may contribute to the development of such interesting project. Sponge is great but way too much resources - intensive.

**Comment by aolko** [comment]
yes, this one is alive and messy, will have to do a cleanup

**Comment by DariusSG** [comment]
So how can we build the server to test it?

**Comment by aolko** [comment]
You can't do that yet.

**Comment by DariusSG** [comment]
Question how did this hybrid server works? 
I actually curious.
