### ISSUE TITLE
Tiny problem how updating forge for using this engine ? 

### ISSUE THREAD

**Issue by halk6000** [KettleFoundation/Kettle#85]
i want play with my friend but forge offer olny 512 ram + run white console i want olny cmd so i search engine to run without this serwer offer more use ram but lots of errors and cant run serwer 
name pack is Rlcraft 
[latest.log](https://github.com/KettleFoundation/Kettle/files/4745169/latest.log)

**Comment by josephworks** [comment]
Forget about updating forge. Downgrade JEI. And prob upgrade java.

**Comment by josephworks** [comment]
There is only 1 error that I saw, and if you are talking about 512mb ram for forge, then forget about playing modded Minecraft...

**Comment by halk6000** [comment]
your engine crack it forge because no run white console,  binpatches.pack.lzma your version this bin more big tham forge i make backup and try recopy updating file into your engine, tiny repair if place minecraft froge is update but close if render world is complete in 85 %. at one time this method to try repair mods for 1.7.10 thermos and work all time. i used java 1.8.66 because is good + 0 errors all time i dont know how programing your project is so large to see and understend how to work this script mayble can repeir if more time sit this and know all dll. + sorry my friend wrote me problem 512 mb but can get 1024 max serwer have 2048 default.

**Comment by josephworks** [comment]
Your version of java was released on November 16, 2015, and since you are not a developer, there is no reason for you to not upgrade. As for the rest of the stuff you typed, I simply can't understand it. Like, what does ``your engine crack it forge because no run white console`` mean?

**Comment by halk6000** [comment]
,,your engine crack it forge because no run white console." ok . so normal serwer forge and minecraft server when run bat  aside from cmd console 
![image](https://user-images.githubusercontent.com/45394417/84575044-bae77d00-adaa-11ea-98ae-4c10e52d95dc.png)  run white console,, serwer console" 
![image](https://user-images.githubusercontent.com/45394417/84575242-f6cf1200-adab-11ea-8feb-a0f82f65b40d.png)

**Comment by josephworks** [comment]
You need to give your server more ram, you are giving it 100Mb, it needs 2Gb+

**Comment by halk6000** [comment]
sorry for again this same problem mayble this log clear for know waht name this problem.
[crash-2020-10-26_12.34.43-server.txt](https://github.com/KettleFoundation/Kettle/files/5438495/crash-2020-10-26_12.34.43-server.txt) i need updating for latest version 1.12.2 
forge-1.12.2-14.23.5.2854 serwer have kettle have 14.23.5.2812 if see on the picture.
![image](https://user-images.githubusercontent.com/45394417/97168498-db780880-1788-11eb-886e-6b0dba1c5ca5.png)
i wait mayble 4 month and now i try download latest version from web kettle but, is noting update and i have this same problem. ty for fix it or instruct me on how to update it yourself.

**Comment by josephworks** [comment]
Kettle is not in development, and I never updated the forge version so I do not know. You have to do a lot of code to update it.

**Comment by halk6000** [comment]
hmm so is problem... core forge is name binpatches.pack.lzma can open online program but is coding binary but cant know how see language and modify for kettle, kettle have old this bin but modify for works, mods and plugins so weight file kettle is more larger tham latest version for forge. forge-1.12.2-14.23.5.2854.  if who try can this file modify when can use this core to updating kettle for forge. I am not a programmer but I am observant in trial and error methods.

**Comment by josephworks** [comment]
Well, it's not that easy. There are also no developers working on kettle at the moment, so I doubt that it will get updated anytime soon. Feel free to try and update it.

**Comment by josephworks** [comment]
If a kettle Dev wants to work on it, they will remove the won't fix tag on this issue.

**Comment by josephworks** [comment]
Last update was a whole entire year ago...

**Comment by halk6000** [comment]
my friend will do it in 2 weeks if he doesn't change his mind. unfortunately he has often changed his mind so far. I urge him to make him modular. two folders one for forge, second for bukkit, when this project start we can easly updating serwer without, looking for files.

**Comment by josephworks** [comment]
Updating a hybrid server IS NOT just switching out forge and bukkit with the latest version... All java devs know where the files that we are looking for are, so that isn't necessary.

**Comment by josephworks** [comment]
Also, please don't have anyone go around changing our file structure, it works perfectly as is.

**Comment by halk6000** [comment]
earlier you said that this is not feasible because there are no programmers to do it. therefore it would be better to make a server for the convenience of people than programmers who come out once a Russian year. not that I'm impatient, but you'd better simplify it or tag where and how what works. this is my opinion. always write a script that makes it eat files from a specific folder and overwrite what is added from the next update without breaking the structure.

**Comment by josephworks** [comment]
Programming kettle is like programming any other java project, it couldn't really be easier. I won't be simplifying it cause I am working on my work instead. We already have a patch based system I think, you can use that I guess..

**Comment by josephworks** [comment]
Actually nevermind, the development team already has a project structure, if you want to develop Kettle, then it is your responsibility to get used to that structure... We aren't going to inconvenience everyone just cause you want a different file structure for some odd reason.

**Comment by halk6000** [comment]
For example, on version 1.7.10 there still were Forge version files which could be replaced to enjoy a newer Forge version without interfering with the Thermos engine's structure. In the case of Kettle and update 1.12.2 these files are no longer rendered so I changed them a bit.It could be that Forge has changed its files to more hidden ones.

**Comment by josephworks** [comment]
> files which could be replaced to enjoy a newer Forge version

No good developer really cares about that. We expect there to be conflicts, and we manually check each file that is conflicting.

What you are asking for is unnecessary work that wouldn't help the developers or the project.

You should only be performing Kettle forge updates if you know exactly what you are doing or know intermediate java.

**Comment by josephworks** [comment]
> Forge has changed its files to more hidden ones.

If you cant find out where the code you are looking for is, then you probably shouldn't mess with the code in the first place.

**Comment by josephworks** [comment]
Since updating forge is not currently an issue, and any java developer can do so, this issue is no longer an issue.
