### ISSUE TITLE
VMW - Special textures 

### ISSUE THREAD

**Issue by Perruchy** [KettleFoundation/Kettle#86]
The textures are very strange, the textures are that of a compass, but they take the textures of other items. Their 3D is completely bugged (I have OptiFine + Fast Render disabled)
Sry for bad ENG
![bug1](https://user-images.githubusercontent.com/60526065/89555574-81624980-d810-11ea-8e0e-843413be703b.PNG)
![bug2](https://user-images.githubusercontent.com/60526065/89555582-832c0d00-d810-11ea-8f4d-2fe955d2a366.PNG)
![2020-08-06_18 12 02](https://user-images.githubusercontent.com/60526065/89555593-86bf9400-d810-11ea-97d2-d55df2fc81ba.png)

**Comment by josephworks** [comment]
I don't think that's our problem, it looks client side. If you disagree, comment or reopen issue.
