### ISSUE TITLE
Why no 1.14.4/1.15/1.16?

### ISSUE THREAD

**Issue by kristibektashi** [KettleFoundation/Kettle#88]
There was a Kettle1.14.4 repository but now it's gone. What happened to it?

**Comment by josephworks** [comment]
If you check the git history, you can see that there hasn't been much (if any) development recently. Maybe that's why there isn't a 1.14.4-1.16.3 version released.

I think GMatrixGames might have removed 1.14.4 as he was the only one working on it or something along those lines.
