### ISSUE TITLE
There is no code!!!

### ISSUE THREAD

**Issue by josephworks** [KettleFoundation/Kettle#9]
Honestly, most of us could care less about the wiki. How about add some code. And if you are trying to prove a point that you are working on kettle, you are failing to do so. Kettle should be renamed Kettle-Docs, cause that's the only thing that exhists here.

**Comment by Timardo** [comment]
This thing (not an issue) should be permanently closed before more immature comments will come and ruin this day @aolko

**Comment by josephworks** [comment]
I have been waiting many months for kettle and now, all the code is deleted and a docs was implemented. Will kettle ever be buildable anyways, or should I not say that cause if I do, this would be closed for "Invalid" or "Too heated"

**Comment by josephworks** [comment]
Calling this issue in mature is your opinion, so please shop calling it that.

**Comment by DragonsAscent** [comment]
That's enough emerald. This issue is being closed.

**Comment by josephworks** [comment]
Why is this "Enough". The issue still hasn't been fixed. There is still no code

**Comment by josephworks** [comment]
And I don't think there will be any (buildable) code

**Comment by josephworks** [comment]
For the time being, I will probably do some pr's to the docs but building code would be nice. And many we should ask the paper team for help
